[project]
name = "fastapi-mcp-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "fastapi-mcp>=0.3.4",
    "pydantic>=2.11.5",
    "uvicorn>=0.34.3",
]
